# Generated by Django 3.2.9 on 2021-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211217_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
