# Generated by Django 3.2.9 on 2021-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/default.jpg', null=True, upload_to='', verbose_name='image'),
        ),
    ]
