# Generated by Django 3.2.9 on 2021-12-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='product.Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
