# Generated by Django 3.2.9 on 2021-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20211217_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='accep_reject_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='checked_out_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='place_at',
            field=models.DateTimeField(null=True),
        ),
    ]
