# Generated by Django 3.2.9 on 2021-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20211218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price_per_unit',
            field=models.PositiveIntegerField(),
        ),
    ]
