# Generated by Django 3.2.9 on 2021-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
