# Generated by Django 3.2.9 on 2021-12-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rating_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
